### ISSUE TITLE
Get white screen at start up on android version 5.1

### ISSUE THREAD

**Issue by sacarlson** [johansten/stargazer#1]
![screenshot_2016-09-21-11-26-29](https://cloud.githubusercontent.com/assets/734826/18698532/348f75b4-7ff5-11e6-8dd9-82c3d5d055cd.png)
Installs ok but when I start the app it ends up with just a white screen.  it is known to work ok on android 6.1 but seems to have problem on android version 5.1,  the phone I tested it on  is a Dogee X6pro with 2G mem.  This has now also been verfied to fail on android 5.1 in an emulator.

**Comment by johansten** [comment]
Thanks a million for helping me out testing. This has been solved, apparently string.startsWith() didn't work, and had to be replaced

**Comment by sacarlson** [comment]
Confirmed it's now working for me on my android 5.1 phone used in this test.  No other problems seen so far with continued test. looks good to me
