### ISSUE TITLE
Blank screen on launch

### ISSUE THREAD

**Issue by mandogofjelly** [johansten/stargazer#11]
Hi.

I just downloaded this wallet, transferred my balance to it and now all I see on launch is a blank screen.

Am I doing something wrong?

<img width="964" alt="screen shot 2017-05-04 at 23 30 25" src="https://cloud.githubusercontent.com/assets/28413931/25727537/ae2aaece-3121-11e7-818b-d047c01e4d18.png">

**Comment by tempofr** [comment]
Same issue for me... Johan mentioned potential dB corruption?!

On 5 May 2017 12:30:52 AM GMT+02:00, mandogofjelly <notifications@github.com> wrote:
>Hi.
>
>I just downloaded this wallet, transferred my balance to it and now all
>I see on launch is a blank screen.
>
>Am I doing something wrong?
>
><img width="964" alt="screen shot 2017-05-04 at 23 30 25"
>src="https://cloud.githubusercontent.com/assets/28413931/25727537/ae2aaece-3121-11e7-818b-d047c01e4d18.png">
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/johansten/stargazer/issues/11

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by johansten** [comment]
Mandogofjelly, you haven't done nothing wrong. I have an update I'm going to release that will fix this, I'm just waiting for my internet connection to come back online again.

**Comment by mandogofjelly** [comment]
Ok, thanks. Appreciate the quick reply and update 👍

**Comment by johansten** [comment]
Fixed in 59b705f
