### ISSUE TITLE
Wallet sent 100 XLM, never received in my exchange acct

### ISSUE THREAD

**Issue by vegasbabyvegas** [johansten/stargazer#16]
Hey I have a transaction where I sent 100 XLM from my Stargazer Wallet to my exchange account wallet on Kraken. It still has not posted and it's been around 6 hours. Any ideas? Thanks.

**Comment by johansten** [comment]
I have two ideas, actually.
1) You forgot do add a memo
2) Kraken are just slow at acknowledging deposits.

Either way,

* Find your stellar address
* Go to stellarchain.io
* Paste your address into the search field in the top right corner
* Find your transaction in the list
* Open it up
* Copy the url to that page, and send it to customer support at Kraken

**Comment by vegasbabyvegas** [comment]
Contacted Kraken with all the info. Thank you!
