### ISSUE TITLE
How to use Stargazer with testnet?

### ISSUE THREAD

**Issue by chevdor** [johansten/stargazer#18]

**Comment by johansten** [comment]
In all the places you can select a network, there's a "show advanced options" button you can click to open. So e.g. when you create an account, when you import an account, when you add a contact,  etc.

**Comment by chevdor** [comment]
I see, I got fooled because the dropdown does not expand if you click on the caret on the right.
It only does when you click the TEXT inside the dropdown. Thanks for the explanation.
