### ISSUE TITLE
Exporting an account should allow it also as string

### ISSUE THREAD

**Issue by chevdor** [johansten/stargazer#19]
a string fits better in a password manager than an image :)

**Comment by blmatthews** [comment]
I agree. Also, does Stargazer import QR codes? I couldn't find a way to do so, which means I need the seed even just to import the account into Stargazer. I solved it by screenshotting the QR code then using http://www.joshjacob.com/mac-development/qrjournal.php to convert the QR code to JSON and copying the key, but that's a lot of frummery just to do something everyone should be doing anyways (storing the seed somewhere securely and backing it up). It would be nice if Stargazer could save the text version of the seed in a file or copy it to the clipboard or something.

**Comment by kfiresmith** [comment]
These are great requests.  I've created an RFE at the top of the stack for this here:  https://github.com/johansten/stargazer/issues/55.

I'm going to close this issue out for now but if you'd like to track the work, please feel free to subscribe to #55.
