### ISSUE TITLE
Building for mobile

### ISSUE THREAD

**Issue by gridworkz** [johansten/stargazer#20]
Hi:

I'm having trouble building for mobile. The command: ionic resources android --icon has been renamed to: ionic cordova resources android -icon and 'ionic state restore' is deprecated. Do you have an updated build command sequence that incorporates Cordova?

I'm on Ubuntu 16.04, node 6.x and a fresh clone of Stargazer.

Cheers,
Dave

**Comment by johansten** [comment]
I'll take a look at it.

`ionic resources` is only really there to build the icons, but `ionic state restore` installs the plugins, so that's the important one.

**Comment by gridworkz** [comment]
Hi Johan:
Thanks for looking at it. We're hoping to use Stargazer with the eCommerce system we're building for street food vendors. We want to make good use of the stellar network...Cheers Dave

**Comment by johansten** [comment]
Updated in #b916d62f
