### ISSUE TITLE
linked accounts

### ISSUE THREAD

**Issue by jedmccaleb** [johansten/stargazer#21]
Somehow the two highlighted accounts got linked. If I click on one the other is also selected.
![rouge gazer](https://cloud.githubusercontent.com/assets/399067/26320198/cad9e55e-3ed6-11e7-8b1f-1c6c973edbfa.png)

Oh maybe they have the same public key? Is there a way to remove one of them?

**Comment by jedmccaleb** [comment]
I figured how to delete one of them. It leaves the other in a weird state till restarting the app. Maybe don't allow you to add an account you already have is the only issue here.

**Comment by johansten** [comment]
Is it just importing the same account twice? I just realized I got that myself, and that's the only explanation I can think of. Will add checks for it.

**Comment by jedmccaleb** [comment]
yeah that is what it was for me

**Comment by johansten** [comment]
Fixed in v1.5.3
