### ISSUE TITLE
Display balance for other tokens than XLM

### ISSUE THREAD

**Issue by chevdor** [johansten/stargazer#22]
In the overview, we can only see the XLM balance.
Seeing other balances would be nice.

**Comment by johansten** [comment]
Other assets *should* be visible, I'm looking at an account right now with XLM and BTC in it, and both show up.

**Comment by chevdor** [comment]
I was actually meaning 'custom issued tokens'.
I issued a token, I can see it in the dropdown when sending, but I see the balance nowhere, neither when sending, nor in the overview.

**Comment by johansten** [comment]
Strange, I just tried it myself, and the asset shows up.

**Comment by chevdor** [comment]
I suspect an issue when the token is seen for the first time:
- I had stargazer running
- I issued the token
- I could not see the token in the overview
- I restarted stargazer
- now I can see the token

**Comment by kfiresmith** [comment]
1.5.4 is dropping soon - I'll try to reproduce this when that comes out, and close the ticket if I can't.

Thanks for reporting!

**Comment by BrentLabasan** [comment]
1.5.4 still has issue where I set up a trustline, do the Update process, but trustline doesn't show up until I restarted app.

**Comment by johansten** [comment]
Fixed in 3e2f21f80b10b934354fa3774e827fdb0dd953d9
