### ISSUE TITLE
UI: When sending, 2 SEND buttons end up visible

### ISSUE THREAD

**Issue by chevdor** [johansten/stargazer#24]
In the UI, when sending, the user ends up seeing 2 SEND button around the end of the process.
While this is no bug, this is very confusing to the user.
A typical user will likely (this is what I did a few times at first, before I paid attention...) click the wrong send button which will cancel the current process and start a new send process, leaving the feeling that "it does not work".
Solution: when the user click send in the footer down the page, immediately mask this footer (containing Receive / Overview/ Send). Once the 'send' wizard is started, those buttons are useless.

**Comment by johansten** [comment]
I've been thinking about making it more wizard-link actually, so that's not a bad idea. Thanks!

**Comment by johansten** [comment]
Fixed in 9ececc8e
