### ISSUE TITLE
Put up a warning on README that funds can get stuck permanently

### ISSUE THREAD

**Issue by taoeffect** [johansten/stargazer#27]
If #26 isn't going to be addressed, could you at least do the ethical / right thing and let people know that using your software can lose people money?

**Comment by tempofr** [comment]
As long as you have a backup of your private key there is no way that this issue will loose your tokens.

Please ensure you always have a backup of your private key.

**Comment by taoeffect** [comment]
How do I use the "backup of the private key" to withdraw these funds? Any instructions / tutorials anywhere?

Sidenote: even if there's a way to recover them, a broken app that holds people's funds should still warn people about this.

**Comment by woodycockburn** [comment]
I found this helpful to get the secret key.  
https://www.mystellar.org/thread-3025.html
then go here 
https://www.stellar.org/account-viewer/#!/

**Comment by taoeffect** [comment]
Thanks @woodycockburn! I'll give it a try...

**Comment by kfiresmith** [comment]
Please do not just trust random QR decoder websites with a QR code that contains your secret key, as the tutorial @woodycockburn posted instructs.  Just a security FYI...

**Comment by kfiresmith** [comment]
Hi @taoeffect  - this issue is really old, and after @woodycockburn posted instructions that seemed to be the end of it, so I'm going to close this issue out.  Please ping this issue if you are still having any problems.  

Thanks!
