### ISSUE TITLE
Show transaction ID in details

### ISSUE THREAD

**Issue by sphinxc0re** [johansten/stargazer#28]
This could be useful for fund recovery

**Comment by kfiresmith** [comment]
Hi @sphinxc0re - thanks for bringing this up.  I've created a complete RFE ticket for this enhancement at https://github.com/johansten/stargazer/issues/53.  

The goal would eventually be for any transaction or address to essentially be a hyperlink to the ledger explorer location for that Stellar network artifact.  

Thanks again!
