### ISSUE TITLE
Trying to send some asset but "send" button is grayed

### ISSUE THREAD

**Issue by jedmccaleb** [johansten/stargazer#3]
I think all trustlines are good. It isn't saying why the send isn't being allowed.

**Comment by johansten** [comment]
Noted.

The trustlines are valid, but underfunded.

**Comment by jedmccaleb** [comment]
You mean in my case? No I had the asset in account A but it wouldn't let me send to account B

**Comment by jedmccaleb** [comment]
I think it just fails in the case where you A is holding an asset and B is receiving that same asset. This is a normal payment but with a different asset. The path payment case seems to work.

**Comment by johansten** [comment]
Ah, got it.. This is a issue in 1.0.0, where amounts are compared as strings.
