### ISSUE TITLE
Scanned QR and interface went crazy

### ISSUE THREAD

**Issue by s-a-y** [johansten/stargazer#34]
Hey, I'm playing with QR codes, I generated one, according to your protocol description
<img width="268" alt="screen shot 2017-10-29 at 11 21 46 am" src="https://user-images.githubusercontent.com/1667781/32139669-f7fa4360-bc9b-11e7-9df8-fa6da9d186d5.png">
I know there is a mistake with empty asset, but stargazer completely freaked out 
![photo_2017-10-29_11-28-07](https://user-images.githubusercontent.com/1667781/32139678-44679ebe-bc9c-11e7-99aa-ca56880ed116.jpg)

**Comment by johansten** [comment]
Fixed in fe72958e9934b4bf74101cd3fd2124e636c39f8e
