### ISSUE TITLE
Desktop version can't connect to the network under Tor

### ISSUE THREAD

**Issue by brunoro** [johansten/stargazer#41]
I downloaded the the AppImage on tails, created an address and sent some coins, but the transaction never showed up. I confirmed that the transaction went through by using an Android device outside of Tor and importing the account.

Is it an issue of the Stellar Network itself or the Desktop client?

**Comment by kfiresmith** [comment]
Sounds like you probably were having a problem reaching the Horizon API endpoint (how clients interact with the Stellar network).

I haven't used Tails, and I don't know if the Tor settings are system-wide at the network stack or if they are done via browser.  You may want to try using 'curl' next time you are on Tor to interact with https://horizon.stellar.org/ and see if you get a response.  

If you can report back with further information about how arbitrary commands seem to interact through Tor back out to the non-dark internet, that would help me understand what you might be seeing.

**Comment by johansten** [comment]
I just got around to trying it under Tor, and didn't find any issue connecting.

**Comment by brunoro** [comment]
@kfiresmith sorry, just saw this issue again. I'll check the connectivity to https://horizon.stellar.org on Tails and report the results. 

@johansten which Tor setup did you use to test it?

**Comment by johansten** [comment]
I ran the Tor browser on macOS, copied it's proxy settings and set up a system-wide proxy, verified that *.onion domains worked in Chrome, and then started the wallet.
