### ISSUE TITLE
Please help , My laptop crashed , Lost my funds and key , please help 

### ISSUE THREAD

**Issue by blockCHAIN9** [johansten/stargazer#45]
My laptop crashed and the key and wallet were on laptop. Developer please help . You can have 10% of my holdings.Please help

**Comment by blockCHAIN9** [comment]
for proof i can show you all the transactions , please help Dev

**Comment by shredding** [comment]
> Developer please help
Unfortunately, if your keys are gone, noone can help you.

> for proof i can show you all the transactions

That's not proof. The transactions are on the blockchain.

**Comment by kfiresmith** [comment]
If you don't have a backup, your best bet is trying to recover the crashed drive or sending it off to a data recovery firm, assuming the amount of funds lost would cover the recovery.
