### ISSUE TITLE
Update minimum required balance to 1 lumen

### ISSUE THREAD

**Issue by nlml** [johansten/stargazer#48]
"Starting at 10 AM PT on January 11, 2018, the base reserve will be reduced 20-fold from 10 lumens to 0.5 lumens."

See https://www.lumenauts.com/blog/stellar-account-minimum-balance-to-reduce-by-20x

Please support this in the app, so the Send button is enabled when the remaining balance will be only 1 lumen.

**Comment by kfiresmith** [comment]
Hi @nlml  - version 1.5.4 is being released shortly and incorporates a dynamic lookup from the latest ledger to calculate reserves.  From then on, this shouldn't ever be a problem again.

https://github.com/johansten/stargazer/commit/40549b1e47b5db5ad2a6f7ce8211c3d3167785d6

Thanks!

**Comment by nlml** [comment]
Thanks!
