### ISSUE TITLE
stellar lumens sent to stargazer wallet address instead of "receive" address

### ISSUE THREAD

**Issue by brycchic** [johansten/stargazer#49]
I accidentally sent my stellar lumens to my stargazer wallet address  instead of my "receive" address .

A friend of mine said he could see that it is in the wallet address. How can I get it in the "receive" address so I can see it? Thank you.

**Comment by kfiresmith** [comment]
Hi @brycchic  - do you have any further details you could provide?  
Screenshots of what you have tried to send, and **text** of the addresses would be a useful starting point to work from.

**Comment by johansten** [comment]
Taken care of over email.
