### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by Hades0103** [johansten/stargazer#51]
There is Application Error when running it.
I run it with **ionic cordova run android**, but there is Application Error.
net::ERR_FILE_NOT_FOUND (file:///android_asset/www/index.html)

**Comment by johansten** [comment]
Have you tried just following the build instructions?
You need to build the main app first.

**Comment by johansten** [comment]
I'm closing this.

I'm getting the same application error message when not building the baseline app before trying to build the ionic app.
