### ISSUE TITLE
Delete account doesn't allow to merge with other account

### ISSUE THREAD

**Issue by corneyl** [johansten/stargazer#52]
I wanted to delete my account by using the account merge operation. So I thought I should use the account delete option, but it just deleted the account. Now my few XLM are lost without warning. Please change this behaviour and add another warning before deleting the account.

**Comment by kfiresmith** [comment]
Hi @corneyl  - you don't happen to have an export of the count by chance?  I could help you re-import it if so.  Otherwise I agree that merge functionality would be welcome.  I'll roll this into an RFE.

**Comment by corneyl** [comment]
I didn't make an export as it's a hassle to save a QR code from a phone. Also I only wanted to merge the account as latest operation, and the account had only about 30XLM in it. But that's my stupidity.

Anyway, I think it's important to show a message what will happen after clicking a button with a lot of impact. Something like: "Do you really want to delete your account? Your funds will be lost if you do not have a backup of your keys." 

I expected a warning or merge options after clicking the delete button.

**Comment by kfiresmith** [comment]
Those are great points.  I'll work on prioritizing safety aspects on the list of RFEs to work on.  Thanks for reporting!

**Comment by johansten** [comment]
c29c470abef6c6a0d08eb7cdb235c204e03542d0 adds a warning message in delete
f91344f36f9375334bfce9528dba2f08dce59592 hides "delete" unless you're in advanced mode
"Close account", which does merging, was added in 3034c6e785432e346f7fb3975385c279ee6b33b4
