### ISSUE TITLE
RFE:  Implement SEP-0005

### ISSUE THREAD

**Issue by kfiresmith** [johansten/stargazer#56]
Please implement SEP-0005, especially test case 4 (password protected 24-word mnemonically derived key seeds). This is especially important to make a common standard in light of repeated issues with people using online seed generators for other currencies, and losing their holdings in cases where the online seed generator was compromised as happened with IOTA Jan 19th.

New and novice users need a convenient and user-friendly standardized way to generate recoverable and password protected seeds using GUI tools.

https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0005.md

**Comment by johansten** [comment]
Import from mnemonic is implemented as of 461f62218dc107abe37f9c7c0e822bf3f336fceb
Changing account creation to use mnemonics will come later

**Comment by johansten** [comment]
Mnemonics in account creation done in 8c2f5253a3b564a26f55b0daf86a620f0308a742
(Except for shared accounts, where it's not needed)
