### ISSUE TITLE
RFE:  Implement basic consolidation merge functionality as an account action

### ISSUE THREAD

**Issue by kfiresmith** [johansten/stargazer#58]
It would be nice to be able to run a merge on at least a basic account (no trustlines etc) as a click-button operation similar to a send.

Potentially if you wanted to make it cover all the use cases, prior art is here: https://github.com/thor1887/stellar-extended-merge

**Comment by johansten** [comment]
The main issue is exchanges. When adding a way to close down an account,  and completely empty it, where are you going to put the funds? Most people want it in an exchange, but most exchanges don't support merging into your deposit account.

There is a solution to it, and a not very complicated one, but it will have to wait until the next major version

**Comment by johansten** [comment]
Basic merge, "Close account",  implemented in 3034c6e785432e346f7fb3975385c279ee6b33b4
