### ISSUE TITLE
QR scanner element should not be present when not on mobile

### ISSUE THREAD

**Issue by kfiresmith** [johansten/stargazer#60]
A minor snag in this being a mobile and desktop/electron app is that it has a QR scanner button that does nothing on the desktop but open a blank 'QR-Scanner' window.  

We should apply some logic so that the button to activate that is not displayed on the desktop app.

**Comment by johansten** [comment]
Linux? I know it works on macOS.

Could make it conditional depending on platform.

**Comment by kfiresmith** [comment]
Apologies, yes this was on Linux.  I should test on a VM with a camera device.  Perhaps the app should actually key off of OS capability rather than type - eg:  Is there a camera device for QR scanner to utilize?  If so, enable, if not, don't show QR scanner button.

**Comment by johansten** [comment]
Fixed in 3ee826cf7ba34f01341822c0c786447afe3f2d08
