### ISSUE TITLE
Stargazer not properly showing balance after account is emptied and merged

### ISSUE THREAD

**Issue by kfiresmith** [johansten/stargazer#63]
Since there is not currently a merge-out functionality, I performed a manual merge using the transaction builder provided by Stellar.  I noticed that after doing so, Stargazer incorrectly determines that I have removed all lumens from the merge-out account *aside* from the network fee.  I haven't looked but I'm guessing that Stargazer is doing some incorrect arithmetic with regard to balance tracking rather than just querying the address for the new balance, which would be zero.
 
![merge_glitch](https://user-images.githubusercontent.com/8343629/35781626-b162864e-09ba-11e8-88dd-1e1da9dac27d.png)

**Comment by johansten** [comment]
Transaction histories in general are quite tricky to get right on Stellar. I'll try to fix that.

**Comment by johansten** [comment]
Fixed in 528af150b4e1c666ad87361287d477780be6e8af

Not sure what to do with transaction histories at the moment, since a zero balance account doesn't display its history (since it doesn't really have one)
