### ISSUE TITLE
RFE:  Provide SHA256 Checksum for Users

### ISSUE THREAD

**Issue by roleerob** [johansten/stargazer#67]
Good Evening,

Would you please consider an enhancement to your GitHub web page in support of your Stargazer Wallet users?  Specifically, to provide us a SHA256 checksum value against which to confirm our download has gone well?

It improves a sense of security to have this.

If you like the idea and, if helpful as an example, I particularly like the details provided by the City of Zion developers of their Neon Wallet => [https://github.com/CityOfZion/neon-wallet/releases]

Respectfully,

Roger

**Comment by johansten** [comment]
Will add signatures. Will also start signing commits/releases.

**Comment by johansten** [comment]
Done in https://github.com/johansten/stargazer/releases/tag/v1.6.0
