### ISSUE TITLE
Should be possible to view your secret key

### ISSUE THREAD

**Issue by jedmccaleb** [johansten/stargazer#7]

**Comment by tempofr** [comment]
Agree - some of the bitcoin wallets AES encrypt it and then allow you to email it to yourself...

Basically there needs to be a simple way of recording it

**Comment by Fonbaron11** [comment]
Where is secret key from the wallet at first place?
do i supposed to see it when i try to export my account?

**Comment by kfiresmith** [comment]
+1 - only being able to export it via a QR code means you need to have a **trusted** QR code reader handy.  
Please embrace the storage method used by Ethereum Mist.

**Comment by jaymutzafi** [comment]
No response to this since Feb?!

**Comment by kfiresmith** [comment]
@jaymutzafi  - because of general usability problems and UI shortcomings such as this, I have given up on any further examination of Stargazer.  I'm using the Python SDK[0] to generate mnemonic keypairs by hand instead, and looking forward to further maturation of the Firefly mobile wallet[1].

[0] https://github.com/kfiresmith/stellar_utils/blob/master/stellar_dw.py
[1] https://github.com/StellarCN/firefly

**Comment by jaymutzafi** [comment]
@kfiresmith Thanks, but this is a bit over my head. I installed this wallet specifically to have a simple GUI. Do you know of another wallet i can transfer the lumens to that is more user friendly?

**Comment by kfiresmith** [comment]
@jaymutzafi  - honestly I'd say either the official paper wallet:  https://github.com/stellar/paper-wallet
Or the official Stellar Desktop Client: http://wallet.stellar.chat/

**Comment by johansten** [comment]
If this is for backup purposes, I think I'm going to go for BIP-39 seed phrases that you have to confirm before the account is actually created. (And display the seed for accounts created before this change)

If it's for pasting into other services, I think that's something that needs to stop ASAP.

**Comment by johansten** [comment]
Unencrypted accounts can view their secret key, in 3e671a4b6aca1df9738b94f7b81b281dedd87a18/d7667d593860b49b21db5a6fc3c4ad1217dec41a
Added seed phrases for account creation in 8c2f5253a3b564a26f55b0daf86a620f0308a742,
and for recovery in 461f62218dc107abe37f9c7c0e822bf3f336fceb
