### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by Heladj** [johansten/stargazer#80]
Hello, I had a problem with my phone and the application was deleted. I had 378 xlm on my wallet. and I do not know my private key to import my wallet on another phone. how to do it please. how to recover my xlm? I only know the address of my wallet. thank you in advance.

**Comment by johansten** [comment]
I'm sorry to say they are gone. I can't do anything to help you, the private key isn't stored anywhere outside of the app unless you've backed it up.
